language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: u4vKjuBYtS9R1wfgo9VMI1NXEV8SqbHwd9eTEOkYTQcJ4Qt3JJnIb9tmsr+I5lMVJNuC7tM022Y91s0fm2fz/mTFCt+XuceHaNgrivJuvFJw14XEzMxOJQcKrntlxAG6iKmK2bn8SKNP7h3SoHg2dKWk7uA21R9QvCtmsc3i72ZXevbIQhMpbvD0OUJjWfS4jHuRV1sVJdNVg1GPiFallQRjHLHI0hi1TYTsjUyNJNBSdGzsYGzlh/ALPV0XUrUT/GfY8hLNu7ZI+JgE68tS01qhZkgofmjpBNyh92bjuFu0AUDB2SrpGEGfGJie/RFdZqDUfzkf3mWIGt06uRC2LKbVvCsYdHIizcDHIfgX8GbW0Ie7dKLmfcEFTj1TXtPYo5Kpkqi+2isBlBw7lnecp0Z4V5fvzTaa4xEGgim3UYibh4zJnOVYg38Zvrd+YaPDzOKx20b4qBjSSt2+U6MwOCG7smHaht1oMJnd0jvWby6cd8dM58EWlBSNVyh7j6N5A2DfFg24oUHxuktSYmQ4uvZXZ9QSe1G8q3HJL06jXg0gSk6vGKbfYAq94D1jk95D1ROEVQan0oOZjL9eOeppI/6E3hnriUMgItelQqofW1ZHBytI+aZRbC3xys96zN2g4niXfyal8XyrjNyGjQjNEv3B/EnDZsp3fDNAh4h0GAs=
  on:
    tags: true
    branches: true
    repo: octoblu/nanocyte-node-trigger
