language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: a2i2HTCaBPJeA2t5ZCfLCBwq6OMCYjLR98mEbwiYNe7pBDSiRnte1LPFeegM8xZG+2o7ayLMlMa7rz/jeI2elwIiI+tLNrfXLUsS9BnRLmKHinIQ7hcnercS39tYw2fYEIcpfVrSzjwXbPrif4Ws4OpYDGuXuXv9WOciqws90sXfQAn4TpqxHxXTCB88vvfXvQcD2xX7TqPOJkskw6clYa4O4saah43+IEI/X0YddxUxAgsNXcfvuXTa5m8yX7gvEh1XEg0X9BkbwzkXCMcbO25nSEjrulbyPi+mjYr7NtgRhX+3w5QwT1+ByARhepL7qFYcA8MqQKsAvqkNmBkIxd1F3yy/NcEDH5kEthHXGY7rDmjtjD5mZwyiRkJI6Vn4oY86lRd/QdhWckdOMxXDGyK91lc4yonmZ9iYUpRHY1lspU7WM8fZvcTA1yh8cm9cV12vUNs8sZpyi5FO9J1JfkD78GYouF8CXZsa9DeCZf5dc0GXaoz6QYnc4QpD/x1VM8bqjzIHVTFPmgRKx5zPdBHRvw+zw9DyybVTBKR1/dCDRmcSiceWgZcJ9Ykhyny2qLKuByA7vLalkI+8e2j4BV60x1+qc9LwmTI6iV4hSkeN81H4SsjhloZ+R2IL6dE/KxCjD1ElWubLTbO/p2klDaZLGg3klxw4VVkPc/JMn2s=
  on:
    tags: true
    all_branches: true
    repo: octoblu/nanocyte-node-trigger
